version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  four-students:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./build.gradle.kts:/app/build.gradle.kts
