create table if not exists "user"
(
    user_id  bigint primary key generated by default as identity,
    login    varchar not null,
    email    varchar not null,
    password varchar not null
);

create table if not exists refresh_token
(
    user_id bigint primary key references "user" on delete cascade,
    token   varchar not null
);

insert into "user"(login, email, password)
values ('user', 'user@mail.ru', 'c621efa7d554249cf490c427979032249c3f75b8'),
       ('admin', 'admin@mail.ru', 'c621efa7d554249cf490c427979032249c3f75b8')