create table if not exists ads
(
    ad_id        bigint primary key generated by default as identity,
    title        varchar not null,
    description  varchar,
    creation_date date,
    price        int,
    type         varchar,
    user_id       bigint references "user"
);

create table if not exists ads_tags
(
    ad_id  bigint references ads,
    tag_id bigint references tags
)